// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb3zSlybIJT_QPLAL_2SHc__yQ6HvQwnw',
    appId: '1:228326302598:web:2b1afdcc65a313ab89c207',
    messagingSenderId: '228326302598',
    projectId: 'my-application-26b82',
    authDomain: 'my-application-26b82.firebaseapp.com',
    storageBucket: 'my-application-26b82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb-cZMvqSqC1EZTdy60oRgMeoRfGUbEWE',
    appId: '1:228326302598:android:5f6ae6ab4cc123d589c207',
    messagingSenderId: '228326302598',
    projectId: 'my-application-26b82',
    storageBucket: 'my-application-26b82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZWBVaFPn54vA6O3Hq86ysyOHFWA-rIr8',
    appId: '1:228326302598:ios:e704ac90c3beb2e389c207',
    messagingSenderId: '228326302598',
    projectId: 'my-application-26b82',
    storageBucket: 'my-application-26b82.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZWBVaFPn54vA6O3Hq86ysyOHFWA-rIr8',
    appId: '1:228326302598:ios:e704ac90c3beb2e389c207',
    messagingSenderId: '228326302598',
    projectId: 'my-application-26b82',
    storageBucket: 'my-application-26b82.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb3zSlybIJT_QPLAL_2SHc__yQ6HvQwnw',
    appId: '1:228326302598:web:219b5f5334db607b89c207',
    messagingSenderId: '228326302598',
    projectId: 'my-application-26b82',
    authDomain: 'my-application-26b82.firebaseapp.com',
    storageBucket: 'my-application-26b82.firebasestorage.app',
  );
}
